### ISSUE TITLE
在analyzer中添加IKTokenFilterFactory分词没有结果

### ISSUE THREAD

**Issue by fachgo** [ittalks/IKAnalyzer2017_6_6_0#1]
fieldType设置如下：
`<analyzer type="query">
		<tokenizer class="org.wltea.analyzer.lucene.IKTokenizerFactory" useSmart="true"/>
        <filter class="org.wltea.analyzer.lucene.IKTokenFilterFactory" useSingle="false" useItself="true" /> 
        
        <filter class="solr.StopFilterFactory" ignoreCase="true" words="stopwords.txt" />
        <filter class="solr.SynonymGraphFilterFactory" synonyms="synonyms.txt" ignoreCase="true" expand="true"/>
        <filter class="solr.LowerCaseFilterFactory"/>
      </analyzer>`
分词解析到IKTokenFilterFactory时就没有结果了

**Comment by Trekkiii** [comment]
问题解决了么？去掉同义词Filter试试。

**Comment by fachgo** [comment]
安装完后第一次使用不好使，可能是重新启动solr后就好使了
